version: 0.2

env:
  variables:
    AWS_REGION: "ca-central-1"
    ECR_REPO_URI: "144425769143.dkr.ecr.ca-central-1.amazonaws.com/cloudapp"
    GITHUB_REPO: "https://github.com/Dhanvi1311/CI-CD.git"
    IMAGE_NAME: "my-app"

phases:      
  pre_build:
    commands:
      - echo Logging in to AWS ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo Cloning the GitHub repository...
      - git clone $GITHUB_REPO
      - cd $(basename $GITHUB_REPO .git)
      - echo Checking out the correct branch...
      - BRANCH=${CODEBUILD_SOURCE_VERSION:-main}
          

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME -f Dockerfile .
      - echo Tagging Docker image...
      - docker tag $IMAGE_NAME:latest $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO_URI:latest
      # - echo Writing image definitions file...
      # - printf '[{"name":"mywebsite","imageUri":"%s"}]' $ECR_REPO_URI:latest > imagedefinitions.json
      # - mkdir -p base_location  # Ensure the directory exists
      # - mv imagedefinitions.json base_location/  # Move the artifact into the base directory

# artifacts:
#   files:
#     - '**/*'  # Include all files recursively from the base directory
#   base-directory: base_location  # Directory to collect artifacts from
#   name: dev-backend-build-artifact  # Name of the artifact
#   discard-paths: no  # Keep directory structure
